vich_uploader:
    db_driver: orm
    twig: true
    form: true

    mappings:
        ad_image:
            uri_prefix: '%app.path.ad_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.ad_image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
